### ISSUE TITLE
double <?xml

### ISSUE THREAD

**Issue by dentarg** [twingly/feedjira.herokuapp.com#1]
![screen shot 2015-11-09 at 11 14 08](https://cloud.githubusercontent.com/assets/42626/11031206/0b7ad0cc-86d3-11e5-80c1-f87975f3cd27.png)

http://www.elle.fi/blogit/nataliaoona/feed

https://feedjira.herokuapp.com/xml?url=http://www.elle.fi/blogit/nataliaoona/feed

Not double with curl

```xml
$ curl http://www.elle.fi/blogit/nataliaoona/feed


<?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xml:base="http://www.elle.fi/blogit/nataliaoona/feed" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Natalia Oona</title>
    <link>http://www.elle.fi/blogit/nataliaoona/feed</link>
    <description>Natalia Oona | Elle</description>
    <language>fi</language>
          <item>
    <title>NEW IN FROM SAINT LAURENT</title>

...
```

**Comment by walro** [comment]
Could it be that it tries to add its own if it's missing on the first line?

**Comment by walro** [comment]
We've updated the gems since this test (feedjira 1.5 -> 2.0). Seems like the feed we've tested with is fine now though.

**Comment by dentarg** [comment]
> We've updated the gems since this test (feedjira 1.5 -> 2.0). Seems like the feed we've tested with is fine now though, so we need another feed.

Or we can just close this one :)

**Comment by walro** [comment]
> Or we can just close this one :)

Hehe yes, closing.
