### ISSUE TITLE
Automatic deploy broken

### ISSUE THREAD

**Issue by walro** [twingly/feedjira.herokuapp.com#2]
It didn't automatically deploy for me last time.

**Comment by jage** [comment]
It was indeed broken, the repository didn't have the webhook notifying Heroku of activity. I've reconnected the Heroku <-> GitHub deploy-connection. Also added HipChat notifications.

![screen shot 2016-04-01 at 21 48 07](https://cloud.githubusercontent.com/assets/7913/14218271/71b97c3e-f853-11e5-98f5-47ba8e987652.png)
